"""Markdown report rendering and writing for ASRH."""
from __future__ import annotations

from collections.abc import Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Final

from asrh import PROJECT_FULL_TITLE, TRACE_SCHEMA_VERSION, get_version
from asrh.report.summary import DEFAULT_MAX_NOTABLE_FAILURES, DEFAULT_REPORT_ENCODING, RunComparison, RunSummary, compare_trace_files, summarize_trace_file, utc_now_iso
from asrh.report.tables import compact_tool_trace, percent, render_case_set_table, render_category_table, render_compared_runs_table, render_comparison_summary_table, render_executive_summary_table, render_failure_delta_table, render_failure_taxonomy_table, render_metric_delta_table, render_run_metadata_table, render_severity_table, render_status_table, render_tool_use_table, truncate

DEFAULT_MARKDOWN_ENCODING: Final[str] = "utf-8"
DEFAULT_MARKDOWN_SUFFIX: Final[str] = ".md"
REPORT_SCHEMA_VERSION: Final[str] = "0.1"
DEFAULT_TOOL_TRACE_LIMIT: Final[int] = 8
DEFAULT_EVIDENCE_LIMIT: Final[int] = 240

class MarkdownReportError(RuntimeError):
    """Base exception for Markdown report rendering and writing."""
class ReportWriteError(MarkdownReportError):
    """Raised when a Markdown report cannot be written."""
ReportOutputError = ReportWriteError
MarkdownWriteError = ReportWriteError

@dataclass(frozen=True, slots=True)
class MarkdownRenderOptions:
    include_traces: bool = True
    max_tool_calls_per_failure: int = DEFAULT_TOOL_TRACE_LIMIT
    max_evidence_chars: int = DEFAULT_EVIDENCE_LIMIT
    include_status_section: bool = True
    include_case_set_section: bool = True

@dataclass(frozen=True, slots=True)
class ReportWriteResult:
    output_path: Path
    report_type: str
    total_cases: int
    compared_runs: int = 1
    written_at: str = ""
    report_schema_version: str = REPORT_SCHEMA_VERSION
    asrh_version: str = get_version()
    def to_dict(self) -> dict[str, object]:
        payload = asdict(self)
        payload["output_path"] = self.output_path.as_posix()
        return payload

MarkdownReportWriteResult = ReportWriteResult
ReportResult = ReportWriteResult
ReportKind = str


def render_single_run_report(summary: RunSummary, *, options: MarkdownRenderOptions | None = None, include_traces: bool | None = None) -> str:
    """Render a single-run ASRH regression report."""
    opts = resolve_options(options=options, include_traces=include_traces)
    lines: list[str] = [
        "# ASRH Regression Report", "", f"Generated by {PROJECT_FULL_TITLE}.", "",
        "## Run Metadata", "", render_run_metadata_table(summary), "",
        "## Executive Summary", "", render_executive_summary_table(summary), "",
        "## Results by Category", "", render_category_table(summary), "",
        "## Results by Severity", "", render_severity_table(summary), "",
    ]
    if opts.include_status_section:
        lines.extend(["## Runner Status", "", render_status_table(summary), ""])
    lines.extend([
        "## Tool Use Summary", "", render_tool_use_table(summary), "",
        "## Failure Taxonomy", "", render_failure_taxonomy_table(summary), "",
        "## Notable Failures", "", render_notable_failures(summary.notable_failures, options=opts), "",
        "## Limitations", "", *render_default_limitations(), "",
        "## Next Steps", "", *render_default_next_steps(), "",
        report_footer_metadata(summary.trace_schema_version),
    ])
    return finish_markdown(lines)


def render_comparison_report(comparison: RunComparison, *, options: MarkdownRenderOptions | None = None, include_traces: bool | None = None) -> str:
    """Render a baseline-versus-variant mitigation comparison report."""
    opts = resolve_options(options=options, include_traces=include_traces)
    lines: list[str] = [
        "# ASRH Mitigation Comparison Report", "", f"Generated by {PROJECT_FULL_TITLE}.", "",
        "## Compared Runs", "", render_compared_runs_table(comparison), "",
        "## Summary", "", render_comparison_summary_table(comparison), "",
        "## Delta vs Baseline", "", render_metric_delta_table(comparison), "",
        "## Failure Taxonomy Delta", "", render_failure_delta_table(comparison), "",
    ]
    if opts.include_case_set_section:
        lines.extend(["## Case Set Check", "", render_case_set_table(comparison), ""])
        if not comparison.case_sets_match:
            lines.extend(["Case sets differ. Interpret metric deltas cautiously.", ""])
    lines.extend([
        "## Interpretation", "", render_comparison_interpretation(comparison), "",
        "## Variant Notable Failures", "", render_notable_failures(comparison.variant.notable_failures, options=opts), "",
        "## Limitations", "", *render_comparison_limitations(), "",
        report_footer_metadata(comparison.variant.trace_schema_version),
    ])
    return finish_markdown(lines)


def render_notable_failures(failures: Sequence[object], *, options: MarkdownRenderOptions | None = None) -> str:
    opts = options or MarkdownRenderOptions()
    if not failures:
        return "No notable failures selected."
    sections: list[str] = []
    for failure in failures:
        evidence = getattr(failure, "evidence", ())
        evidence_text = "; ".join(truncate(item, opts.max_evidence_chars) for item in evidence) if evidence else "—"
        sections.extend([
            f"### {getattr(failure, 'case_id', 'unknown')}", "",
            f"- Category: {getattr(failure, 'category', 'unknown')}",
            f"- Severity: {getattr(failure, 'severity', 'unknown')}",
            f"- Overall verdict: {getattr(failure, 'overall', 'unknown')}",
            f"- User goal: {truncate(getattr(failure, 'user_goal', 'unknown'), opts.max_evidence_chars)}",
            f"- Attack: {truncate(getattr(failure, 'attack', 'unknown'), opts.max_evidence_chars)}",
            f"- Checker failure: {getattr(failure, 'checker_failure', getattr(failure, 'checker', '—'))}",
            f"- Failure class: {getattr(failure, 'failure_class', '—')}",
            f"- Evidence: {evidence_text}",
        ])
        errors = getattr(failure, "errors", ())
        if errors:
            sections.extend(["", "Errors:", "", "\n".join(f"- {item}" for item in errors)])
        if opts.include_traces:
            sections.extend(["", "Tool trace:", "", compact_tool_trace(getattr(failure, "tool_calls", ()), limit=opts.max_tool_calls_per_failure)])
        sections.append("")
    return "\n".join(sections).rstrip()


def render_comparison_interpretation(comparison: RunComparison) -> str:
    return "\n".join(f"- {line}" for line in comparison.interpretation)


def render_default_limitations() -> list[str]:
    return [
        "- Metrics are derived from JSONL trace fields and deterministic checker outputs.",
        "- Missing fields are reported as `unknown` rather than inferred.",
        "- String-based checkers can miss paraphrased or indirect disclosures.",
        "- Utility checks based on required evidence are intentionally crude for MVP reproducibility.",
        "- Synthetic cases are useful for regression testing but do not by themselves prove real-world safety.",
    ]


def render_default_next_steps() -> list[str]:
    return [
        "- Inspect notable failures before changing cases, checkers, or mitigations.",
        "- Compare this run against a guarded mitigation mode before claiming safety improvement.",
        "- Preserve JSONL traces so failures remain reproducible.",
    ]


def render_comparison_limitations() -> list[str]:
    return [
        "- This comparison is descriptive and does not prove statistical significance.",
        "- Case sets should match before interpreting mitigation deltas strongly.",
        "- Tool-policy guards can improve safety by blocking actions too aggressively, so utility deltas matter.",
        "- Prompt wording and strict JSON action formatting can affect model behavior.",
    ]


def report_footer_metadata(trace_schema_version: str | None = None) -> str:
    return "\n".join(["## Report Metadata", "", f"- Report schema version: `{REPORT_SCHEMA_VERSION}`", f"- Trace schema version: `{trace_schema_version or TRACE_SCHEMA_VERSION}`", f"- ASRH version: `{get_version()}`", f"- Generated at: `{utc_now_iso()}`"])


def write_single_run_report(run_path: str | Path, output_path: str | Path, *, max_failures: int = DEFAULT_MAX_NOTABLE_FAILURES, include_traces: bool = True, overwrite: bool = False, encoding: str = DEFAULT_REPORT_ENCODING) -> ReportWriteResult:
    summary = summarize_trace_file(run_path, max_failures=max_failures, encoding=encoding)
    output = write_markdown(render_single_run_report(summary, include_traces=include_traces), output_path, overwrite=overwrite, encoding=encoding)
    return ReportWriteResult(output_path=output, report_type="single-run", total_cases=summary.total_cases, compared_runs=1, written_at=utc_now_iso())


def write_comparison_report(baseline_path: str | Path, variant_path: str | Path, output_path: str | Path, *, max_failures: int = DEFAULT_MAX_NOTABLE_FAILURES, include_traces: bool = True, overwrite: bool = False, encoding: str = DEFAULT_REPORT_ENCODING) -> ReportWriteResult:
    comparison = compare_trace_files(baseline_path, variant_path, max_failures=max_failures, encoding=encoding)
    output = write_markdown(render_comparison_report(comparison, include_traces=include_traces), output_path, overwrite=overwrite, encoding=encoding)
    return ReportWriteResult(output_path=output, report_type="comparison", total_cases=max(comparison.baseline.total_cases, comparison.variant.total_cases), compared_runs=2, written_at=utc_now_iso())


def write_markdown(markdown: str, output_path: str | Path, *, overwrite: bool = False, encoding: str = DEFAULT_REPORT_ENCODING) -> Path:
    output = Path(output_path).expanduser()
    if output.suffix.lower() != DEFAULT_MARKDOWN_SUFFIX:
        raise ReportWriteError(f"Markdown report output must use the {DEFAULT_MARKDOWN_SUFFIX} suffix: {output}")
    if output.exists() and output.is_dir():
        raise ReportWriteError(f"Report output path points to a directory: {output}")
    if output.exists() and not overwrite:
        raise ReportWriteError(f"Report output already exists: {output}; pass overwrite=True to replace it")
    output.parent.mkdir(parents=True, exist_ok=True)
    try:
        output.write_text(markdown.rstrip() + "\n", encoding=encoding)
    except OSError as exc:
        raise ReportWriteError(f"Failed to write Markdown report to {output}: {exc}") from exc
    return output


def resolve_options(*, options: MarkdownRenderOptions | None, include_traces: bool | None) -> MarkdownRenderOptions:
    if options is None:
        return MarkdownRenderOptions(include_traces=True if include_traces is None else include_traces)
    if include_traces is None or include_traces == options.include_traces:
        return options
    return MarkdownRenderOptions(include_traces=include_traces, max_tool_calls_per_failure=options.max_tool_calls_per_failure, max_evidence_chars=options.max_evidence_chars, include_status_section=options.include_status_section, include_case_set_section=options.include_case_set_section)


def finish_markdown(lines: list[str]) -> str:
    return "\n".join(lines).rstrip() + "\n"

# Aliases expected by earlier files and docs.
render_single_run_markdown = render_single_run_report
render_run_markdown = render_single_run_report
render_run_report = render_single_run_report
render_regression_report = render_single_run_report
render_records_report = render_single_run_report
render_comparison_markdown = render_comparison_report
render_mitigation_comparison_report = render_comparison_report
render_compare_report = render_comparison_report
generate_single_run_report = write_single_run_report
generate_comparison_report = write_comparison_report
write_run_report = write_single_run_report
write_regression_report = write_single_run_report
write_mitigation_comparison_report = write_comparison_report
write_compare_report = write_comparison_report
write_markdown_report = write_markdown
clean_markdown = lambda text: text.rstrip() + "\n"
join_evidence = lambda evidence: "; ".join(str(item) for item in evidence)
__all__: Final[tuple[str, ...]] = tuple(name for name in globals() if not name.startswith("_"))
